[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexer = {path = "../lexer"}
parser = {path = "../parser"}
llvm = {path = "../llvm"}
inkwell = {path = "../inkwell"}
path-absolutize = "3.0.11"
