[package]
name = "inkwell"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "120"
either = "1.6.1"
once_cell = "1.4.1"
parking_lot = "0.11"