[package]
name = "llvm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = {path = "../ast"}
inkwell = { path = "../inkwell"}



[dev-dependencies]
parser = { path = "../parser"}
lexer = {path = "../lexer"}
insta = "1.7.2"