[package]
name = "llvm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = {path = "../ast"}
inkwell = { path = "../inkwell"}
lexer = {path = "../lexer"}


[dev-dependencies]
parser = { path = "../parser"}
insta = "1.7.2"
test-utils = {path = "../test-utils"}