[package]
name = "llvm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = {path = "../ast"}
inkwell = { path = "../inkwell"}
lexer = {path = "../lexer"}
indexmap = "1.7.0"
either = "1.6.1"
parser = { path = "../parser"}
path-absolutize = "3.0.11"


[dev-dependencies]
insta = "1.7.2"
test-utils = {path = "../test-utils"}